name: Build Docker Images 

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"

jobs:
  build:
    name: Build Docker Images 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-test.txt
      - name: Get refs - this will be used as tags later on
        shell: bash
        run: |
          echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"
        id: getrefs
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: "Dockerfile"
          
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            {{ cookiecutter.stack_org }}/{{ cookiecutter.stack_name }}:${{ steps.getrefs.outputs.sha12 }}, {{ cookiecutter.stack_org }}/{{ cookiecutter.stack_name }}:latest
          
      - name: Run tests 
        run: python -m pytest tests